apiVersion: v1
kind: ConfigMap
metadata:
  name: lunch-swap0-config
  labels:
    app.kubernetes.io/name: lunch-swap0
data:
  INSTANCE_DOMAIN: 'api.topia.io'
  INSTANCE_PROTOCOL: 'https'
  INTERACTIVE_KEY: 'k6wxCPb8QJhL6Nfqk9cT'
  NODE_ENV: 'production'
  PORT: '3000'
